name: Build Windows EXE

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build:
runs-on: windows-latest

```
steps:
- name: Checkout code
  uses: actions/checkout@v4

- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.11'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pyinstaller
    if exist requirements.txt pip install -r requirements.txt

- name: Build EXE with PyInstaller
  run: |
    pyinstaller --onefile --windowed bmw_maint_tracker.py

- name: Upload EXE as artifact
  uses: actions/upload-artifact@v4
  with:
    name: BreakMyWallet
    path: dist/bmw_maint_tracker.exe
```
