name: Test GitHub Actions Setup

on:
push:
branches:
- main

jobs:
test:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v4

```
  - name: Say Hello
    run: |
      echo "✅ GitHub Actions is configured correctly!"
      echo "Repository: ${{ github.repository }}"
      echo "Branch: ${{ github.ref_name }}"
```
